name: Publish Web to Docker

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-web:
    name: Publish Web
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Github Repository - Lowercase
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}

      - name: Get latest tag
        id: get-tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

      - name: Get Semver from latest tag
        id: replaced
        uses: frabert/replace-string-action@v2
        with:
          pattern: '(@[^/]+/)?[^@]+@'
          string: ${{ steps.get-tag.outputs.tag }}
          replace-with: ''

      - name: Build and push to Docker - Web
        if: contains(steps.get-tag.outputs.tag, 'web')
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./web
          file: ./web/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/web:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/web:${{ steps.replaced.outputs.replaced }}
          build-args: |
            GIT_SHA=${{ github.sha }}
